### PR TITLE
Feature/setup cypress for e2e testing

### LINKED ISSUE #65: Setup Cypress for E2E testing
**Is your enhancement related to a problem? Please describe.**

See overall concept in the [OSBP guide](https://10up.github.io/Open-Source-Best-Practices/testing/#e2e-testing) and example setups on [Simple Podcasting](https://github.com/10up/simple-podcasting), [Restricted Site Access](https://github.com/10up/restricted-site-access), and https://github.com/10up/ElasticPress/pull/2446.

**Describe the solution you'd like**

- [ ]   add base GitHub Action
- [ ]   add .wp-env.json
- [ ]   add base docker files
- [ ]   update package.json / package lock files
- [ ]   add cypress tests
- [ ]   remove any WP Acceptance components

**Designs**

n/a

**Describe alternatives you've considered**

n/a

**Additional context**

https://github.com/10up/cypress-wp-setup/ && https://github.com/10up/cypress-wp-utils will be helpful in getting this spun up and some initial test commands to leverage.

### PR DESCRIPTION
**Pull request by barneyjeffries**
### Description of the Change

This PR adds Cypress for e2e testing, configured and with 2 tests set-up:

1. block.test - the test creates a new classic post with dummy content, opens the post and checks content has been converted to blocks
2. admin.test - the test logs in and deactivates and activates the plugin

Closes #65

### How to test the Change

1. Pull changes
2. Run `npm install`
3. Build assets: `npm run build`
4. Start local environment: `npm run env:start`
5. Open Cypress for testing: `npm run cypress:open`
6. Use Cypress GUI to run tests and verify they are working

### Changelog Entry

> Added -  e2e testing with Cypress

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by barneyjeffries** [comment]
@cadic I seem to be having the same issue I had with [this PR](https://github.com/10up/retro-winamp-block/pull/87) - the tests are failing. I tried bumping the WP version.

Would you mind reviewing and letting me know what you think the issue might be?

**Comment by jeffpaul** [comment]
@iamdharmesh note this is waiting your review

**Comment by jeffpaul** [comment]
@10up/open-source-practice Cypress e2e PR up for review

**Review by iamdharmesh — COMMENTED** [review]
Hi @barneyjeffries, 

Thanks a lot for the Great work here, the code looks good to me. 

I noticed that 1 E2E test is failing. Could you please help to check and fix it?

We are good to merge this once we fix the failing e2e test. 

Thanks
cc: @jeffpaul

**Review by Sidsector9 — APPROVED** [review]

**Pull request merged**
