### PR TITLE
Bump tested up to WordPress 6.0

### LINKED ISSUE #63: Test against WordPress 6.0
### Is your enhancement related to a problem? Please describe.

Is your enhancement related to a problem? Please describe.
Once WordPress 6.0 is released, we'll want to test Convert to Blocks to see if any incompatibility issues arise.

Describe the solution you'd like

- [ ] test Convert to Blocks on WordPress 6.0
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

Designs
n/a

Describe alternatives you've considered
None

Additional context
Related: #58, #49, #32, #23. 

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by cadic**
### Description of the Change

The plugin has been tested against WordPress 6.0.

- [x] The post created in Classic Editor with elements: Heading, List, Image, Blockquote
- [x] Post opened for edit in Block Editor
- [x] The content was converted to blocks on the fly

Closes #63

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

> Changed - Bump WordPress version "tested up to" 6.0

### Credits

Props @cadic

### CODE REVIEW

**Comment by cadic** [comment]
Unit tests are fixed in #69

**Review by iamdharmesh — APPROVED** [review]
:rocket:

**Comment by jeffpaul** [comment]
@cadic looks like something's still off with the unit tests here

**Comment by cadic** [comment]
@jeffpaul resolved after merging `develop` in with PHPUnit fix from #69

**Pull request merged**
